# Generated by Django 5.0.6 on 2026-05-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
